# version: '3'

services:
  frontend:
      container_name: front
      build: ./front  # Assuming the frontend Dockerfile is in a folder named 'frontend'
      ports:
        - "8080:80"
      networks:
        - my-net
      depends_on:
        - web  # Make sure the backend is running
        - backend
      volumes:
        - ./front:/usr/share/nginx/html
  web:
    container_name: web
    build: ./project
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on: 
      - db
    environment:
      - DB_NAME=ft_transcandencedb
      - DB_USER=othmane
      - DB_PASSWORD=otitebah1234
      - DB_HOST=db
      - DB_PORT=5432
      - private_key=08fdb79d0797a2f3be23e65c04b7ea373873132a8b0c1952298ebd103dafa656
      - PYTHONUNBUFFERED=1
    networks:
      - my-net
    volumes:
      - ./project:/usr/src/app

  db:
    container_name: database
    image: postgres:14
    environment:
      POSTGRES_DB: ft_transcandencedb
      POSTGRES_USER: othmane
      POSTGRES_PASSWORD: otitebah1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-net

  backend:
      container_name: backend
      build: ./backend
      image: backend
      restart: always
      ports:
        - "8001:8001"
      volumes:
        - ./backend:/backend
      networks:
        - my-net
      environment:
        - PYTHONUNBUFFERED=1
        - PYTHONDONTWRITEBYTECODE=1

  chat:
      build: ./ChatBackend
      command: ["./wait-for-it.sh", "redis:6379", "--", "daphne", "-b", "0.0.0.0", "-p", "8002", "chatapp.asgi:application"]
      ports:
        - "8002:8002"
      networks:
        - my-net
      volumes:
        - ./ChatBackend:/app
      depends_on:
        - redis
      environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - DJANGO_SETTINGS_MODULE=chatapp.settings
        - DB_NAME=ft_transcandencedb
        - DB_USER=othmane
        - DB_PASSWORD=otitebah1234
        - DB_HOST=db
        - DB_PORT=5432

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
    - my-net

volumes:
  postgres_data:

networks:
  my-net: